# Generated by Django 2.0.12 on 2019-12-06 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=200)),
                ('image_name', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('topic_type', models.CharField(choices=[('YT', 'Youtube'), ('UR', 'URL')], default='YT', max_length=2)),
                ('order', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TopicContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('video_id', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('topic_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TopicCategory')),
            ],
        ),
    ]
