# Generated by Django 2.0.12 on 2019-12-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiccategory',
            name='image_name',
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='image_photo',
            field=models.ImageField(default='NULL', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='url',
            field=models.URLField(),
        ),
    ]
