# Generated by Django 2.0.12 on 2019-12-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191206_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiccontent',
            name='topic_category',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='topic_type',
        ),
        migrations.DeleteModel(
            name='TopicContent',
        ),
    ]
