# Generated by Django 2.0.12 on 2019-12-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191206_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_reg', models.EmailField(max_length=254)),
                ('username_reg', models.TextField()),
                ('password_reg', models.TextField()),
            ],
        ),
    ]
