# Generated by Django 2.0.12 on 2019-12-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='email_reg',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='password_reg',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='username_reg',
            new_name='username',
        ),
    ]
