# Generated by Django 2.0.12 on 2019-12-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191206_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg',
        ),
    ]
