# Generated by Django 2.0.12 on 2019-12-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicCategory',
            new_name='Blogs',
        ),
    ]
